### ISSUE TITLE
[FEATURE REQUEST] Docs?

### ISSUE THREAD

**Issue by adrian2x** [101arrowz/precache-manifest#2]
## The problem
There are no docs on how to set this up with an existing service worker setup. How do I tell parcel where my sw is to have the plugin write the precached assets into it?

## Possible solution
Add a configuration guide to the README.

**Comment by 101arrowz** [comment]
There is no configuration. Parcel 2 makes it possible to, with 100% certainty, know which files are service workers. The manifest injects into every service worker found. Does that help @adrian2x?

**Comment by adrian2x** [comment]
So the Parcel 2 docs are not clear on how to setup a service worker build. I think it needs to be setup as a target with context set to `service-worker` but I am not sure, I can't find a guide/recipe or specific instructions for service worker.
When I started looking for guides I stumbled upon your projects and it looks like they could help me with:
* Generating a manifest with links to the dynamically built (hashed) assets
* Preaching said dynamic assets

What I tried:
Installing this plugin & rebuilding

This did not modify my manifest or generate any precaching config, so I am not sure I'm using it right.
It would be great to see a self contained example of this plugin integrated with Parcel, or at least more info in the README about how to add this to an existing setup and what to expect.

**Comment by 101arrowz** [comment]
It's actually quite simple to use service workers in Parcel 2. Parcel has always been good with zero config, and similarly here, you don't need any config to make service workers function.

`package.json`:
```json
{
    "devDependencies": {
        "parcel": "^2.0.0-nightly.xxx"
        "parcel-config-precache-manifest": "^0.0.2"
    }
    "scripts": {
        "build": "parcel build public/index.html"
    }
}
```

`.parcelrc`:
```json
{
    "extends": ["@parcel/config-default", "parcel-config-precache-manifest"]
}
```

`public/index.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <script src="../src/index.js"></script>
</body>
</html>
```

`src/index.js`:
```js
if ('serviceWorker' in navigator) {
  // This is the key line: Parcel auto-detects this is a service worker
  navigator.serviceWorker.register('sw.js');
}
```

`src/sw.js`:
```js
// Everything should work here
console.log(self.__precacheManifest);
```

`npm build` should give you a working service worker with an injected manifest.

**Comment by 101arrowz** [comment]
@adrian2x Did that work for you?

**Comment by kkirby** [comment]
Here's the relevant documentation on Parcel's website: https://parceljs.org/languages/javascript/#service-workers

**Comment by 101arrowz** [comment]
Yeah with `@parcel/service-worker` this package is obsolete.
